/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:aa6f94e4-619c-4599-99ee-dd0885c46ea8",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_at7AAhi2t",
    "aws_user_pools_web_client_id": "2bnla356fl7nbo28falir2658s",
    "oauth": {}
};


export default awsmobile;
